apiVersion: apps/v1
kind: Deployment
metadata:
  name: whitestar-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-for-labels
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: sample-for-container
        image: sample-for-image
        ports:
        - containerPort: 8080